/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.chatapp.view;

import com.chatapp.model.Account;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class ChangeAvatarFrm extends javax.swing.JFrame {
    private Account account;
    private DataInputStream input;
    private DataOutputStream output;
    private Socket socket;
    private String host = "localhost";
    private int port = 9999;
    private ChatFrm chatFrame;
    /**
     * Creates new form ChangeAvatarFrm
     */
    public ChangeAvatarFrm(ChatFrm chat, Account account, DataInputStream dis, DataOutputStream dos) {
        initComponents();
        initComponents();
        chatFrame = chat;
        this.account = account;
        input = dis;
        output = dos;
        labelAvatar.setIcon(new javax.swing.ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/chatapp/image/" + account.getAvatar())).getScaledInstance(237, 237, Image.SCALE_SMOOTH)));
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnSaveChanges = new javax.swing.JButton();
        btnChooseAvatar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelAvatar = new javax.swing.JLabel();
        labelAvatarText = new javax.swing.JLabel();
        btn_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(null);

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(51, 51, 51));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chatapp/image/back.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(20, 10, 30, 30);

        btnSaveChanges.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSaveChanges.setForeground(new java.awt.Color(19, 142, 24));
        btnSaveChanges.setText("Save Changes");
        btnSaveChanges.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveChanges.setOpaque(true);
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveChanges);
        btnSaveChanges.setBounds(430, 320, 140, 48);

        btnChooseAvatar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnChooseAvatar.setForeground(new java.awt.Color(51, 51, 51));
        btnChooseAvatar.setText("Choose new Avatar");
        btnChooseAvatar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChooseAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseAvatarActionPerformed(evt);
            }
        });
        jPanel1.add(btnChooseAvatar);
        btnChooseAvatar.setBounds(310, 240, 260, 48);

        jPanel2.setBackground(new java.awt.Color(214, 253, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255)));
        jPanel2.setLayout(null);

        labelAvatar.setBackground(new java.awt.Color(255, 255, 255));
        labelAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAvatar.setOpaque(true);
        jPanel2.add(labelAvatar);
        labelAvatar.setBounds(10, 10, 240, 237);

        labelAvatarText.setFont(new java.awt.Font("Freestyle Script", 0, 30)); // NOI18N
        labelAvatarText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAvatarText.setText("Avatar");
        jPanel2.add(labelAvatarText);
        labelAvatarText.setBounds(10, 260, 240, 45);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 60, 260, 310);

        btn_Cancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Cancel.setForeground(new java.awt.Color(255, 0, 51));
        btn_Cancel.setText("Hủy");
        btn_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Cancel);
        btn_Cancel.setBounds(310, 320, 100, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        chatFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        int tmp = JOptionPane.showConfirmDialog(rootPane, "Are you sure to save the changes?");
        if (tmp == 0) {
            changeAvatar();
        }
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    private void btnChooseAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseAvatarActionPerformed
        String link = System.getProperty("user.dir");
        System.out.println(link);
        final JFileChooser fileDialog = new JFileChooser(link + "\\src\\comm\\chatapp\\image\\");
        int returnVal = fileDialog.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            java.io.File file = fileDialog.getSelectedFile();
            labelAvatar.setIcon(new javax.swing.ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/chatapp/image/" + file.getName()))));
            account.setAvatar(file.getName());
        }
    }//GEN-LAST:event_btnChooseAvatarActionPerformed

    private ImageIcon originalImageIcon;
    
    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        if (originalImageIcon != null) {
            // Đặt lại hình ảnh của labelAvatar thành hình ảnh ban đầu
            labelAvatar.setIcon(originalImageIcon);
        } else {
            // Nếu không có hình ảnh ban đầu, đặt hình ảnh của labelAvatar thành null
            labelAvatar.setIcon(null);
        }
    }//GEN-LAST:event_btn_CancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChooseAvatar;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAvatar;
    private javax.swing.JLabel labelAvatarText;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("")));
    
    }

    private boolean changeAvatar() {
        ConnectToServer();
        try {
            output.writeUTF("Change Avatar");
            output.writeUTF(account.getUserName());
            output.writeUTF(account.getAvatar());
            String respon = input.readUTF();
            if (respon.equals("Update successful")) {
                JOptionPane.showMessageDialog(rootPane, "Change Avatar Successful");
                chatFrame.setAvatar(account.getAvatar());
                return true;
            }
        } catch (IOException ex) {
            Logger.getLogger(ChangeAvatarFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    public void ConnectToServer() {
        try {
            if (socket != null) {
                socket.close();
            }
            System.out.println("connect 1");
            socket = new Socket(host, port);
            System.out.println("connect 2");
            this.input = new DataInputStream(socket.getInputStream());
            this.output = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
}
